@startuml
class Alquiler {
    + IdAlquiler : int <<get>> <<set>>
    + NombreUsuario : string <<get>> <<set>>
    + ApellidosUsuario : string <<get>> <<set>>
    + DNI : string <<get>> <<set>>
    + FechaAlquiler : DateTime <<get>> <<set>>
    + MetodoPago : string <<get>> <<set>>
    + NumeroTelefono : string <<get>> <<set>>
    + PrecioTotal : decimal <<get>> <<set>>
    + Alquiler()
    + Alquiler(idAlquiler:int, nombreUsuario:string, apellidosUsuario:string, dni:string, fechaAlquiler:DateTime, metodoPago:string, numeroTelefono:string, precioTotal:decimal)
    + <<override>> Equals(obj:object?) : bool
}
@enduml
