        @startuml
class Material {
    + Id : int <<get>> <<set>>
    + Descripcion : string <<get>> <<set>>
    + FechaHora : DateTime <<get>> <<set>>
    + Lugar : string <<get>> <<set>>
    + Monitor : string <<get>> <<set>>
    + Nivel : string <<get>> <<set>>
    + PlazasDisponibles : int <<get>> <<set>>
    + PrecioUnitario : decimal <<get>> <<set>>
    + TipoDeporteId : int <<get>> <<set>>
    + TipoDeporte : TipoDeporte <<get>> <<set>>
}
@enduml
