 @startuml
class Material {
    + Id : int <<get>> <<set>>
    + PlazasReservadas : int <<get>> <<set>>
    + Precio : decimal <<get>> <<set>>
    + Observaciones : string <<get>> <<set>>
    + ClaseDeportivaId : int <<get>> <<set>>
    + ClaseDeportiva : ClaseDeportiva <<get>> <<set>>
    + InscripcionId : int <<get>> <<set>>
    + Inscripcion : Inscripcion <<get>> <<set>>
}
@enduml
