@startuml
class TipoDeporte {
    + Id : int <<get>> <<set>>
    + Competiciones : string <<get>> <<set>>
    + Materiales : List<Material> <<get>> <<set>>
    + Nombre : string <<get>> <<set>>
    + NombreTipoDeporte : string <<get>> <<set>>
    + Pistas : List<Pista> <<get>> <<set>>
    + TipoDeporte()
    + description() : string <<get>> <<set>>
    + TipoDeporte(id:int, nombre:string, nombreTipoDeporte:string, competiciones:string)
    + <<override>> Equals(obj:object?) : bool
}
@enduml
